# Generated by Django 6.0 on 2025-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('value', models.TextField()),
                ('editable', models.BooleanField(default=True)),
                ('desc', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
