# Generated by Django 5.2.5 on 2025-11-24 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_role_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '目录'), (2, '菜单'), (3, '按钮')], default=2, verbose_name='类型')),
                ('path', models.CharField(blank=True, max_length=128, verbose_name='路由/URL')),
                ('component', models.CharField(blank=True, max_length=128, verbose_name='前端组件')),
                ('icon', models.CharField(blank=True, max_length=32, verbose_name='图标')),
                ('weight', models.PositiveSmallIntegerField(default=100, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('perms', models.CharField(blank=True, max_length=128, verbose_name='权限标识')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='父级')),
                ('roles', models.ManyToManyField(blank=True, related_name='menus', to='user.role', verbose_name='可见角色')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['weight', 'id'],
            },
        ),
    ]
