# Generated by Django 5.2.5 on 2025-12-01 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='表号')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='安装地址')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建档时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '电表档案',
                'verbose_name_plural': '电表档案',
                'db_table': 'meter',
            },
        ),
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月份')),
                ('kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='用电量(kWh)')),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='电费(元)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usages', to='power.meter', verbose_name='电表')),
            ],
            options={
                'verbose_name': '月度用电量',
                'verbose_name_plural': '月度用电量',
                'db_table': 'monthly_usage',
                'ordering': ['-year', '-month'],
                'unique_together': {('meter', 'year', 'month')},
            },
        ),
    ]
