# Generated by Django 6.0 on 2025-12-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='日期')),
                ('kwh', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='用电量(kWh)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to='power.meter', verbose_name='电表')),
            ],
            options={
                'db_table': 'daily_usage',
                'ordering': ['-day'],
                'unique_together': {('meter', 'day')},
            },
        ),
    ]
