# Generated by Django 6.0 on 2025-12-06 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0002_dailyusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMeterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_json', models.JSONField(blank=True, default=dict, verbose_name='最新原始实时数据')),
                ('realtime_series', models.JSONField(blank=True, default=list, verbose_name='实时曲线点')),
                ('trend_day', models.JSONField(blank=True, default=dict, verbose_name='日趋势快照')),
                ('trend_week', models.JSONField(blank=True, default=dict, verbose_name='周趋势快照')),
                ('trend_month', models.JSONField(blank=True, default=dict, verbose_name='月趋势快照')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_snapshots', to='power.meter', verbose_name='电表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_meter_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '前端电表快照',
                'verbose_name_plural': '前端电表快照',
                'db_table': 'client_meter_snapshot',
                'unique_together': {('user', 'meter')},
            },
        ),
    ]
