# Generated by Django 6.0 on 2025-12-06 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0003_clientmetersnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmetersnapshot',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientmetersnapshot',
            name='latest_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clientmetersnapshot',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_snapshots', to='power.meter'),
        ),
        migrations.AlterField(
            model_name='clientmetersnapshot',
            name='realtime_series',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clientmetersnapshot',
            name='trend_day',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clientmetersnapshot',
            name='trend_month',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clientmetersnapshot',
            name='trend_week',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clientmetersnapshot',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientmetersnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_meter_snapshots', to=settings.AUTH_USER_MODEL),
        ),
    ]
