# Generated by Django 6.0 on 2025-12-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0004_alter_clientmetersnapshot_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyusage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='monthlyusage',
            options={},
        ),
        migrations.RemoveField(
            model_name='dailyusage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='address',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='created',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monthlyusage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='monthlyusage',
            name='money',
        ),
        migrations.AddField(
            model_name='meter',
            name='energy_today',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_power_w',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_ts',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyusage',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailyusage',
            name='kwh',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyusage',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.meter'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='kwh',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.meter'),
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='dailyusage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='meter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='monthlyusage',
            table=None,
        ),
    ]
