# Generated by Django 6.0 on 2025-12-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0006_meter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.IntegerField()),
                ('kwh', models.FloatField(default=0)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.meter')),
            ],
            options={
                'unique_together': {('meter', 'day', 'hour')},
            },
        ),
    ]
