# Generated by Django 6.0 on 2025-12-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0007_hourlyusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('high_power', '功率过高'), ('sudden_usage', '用电突增'), ('voltage_issue', '电压异常'), ('fluctuation', '功率波动异常')], max_length=50)),
                ('desc', models.TextField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.meter')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_kwh', models.FloatField(default=0)),
                ('total_fee', models.FloatField(default=0)),
                ('generate_time', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.meter')),
            ],
            options={
                'unique_together': {('meter', 'year', 'month')},
            },
        ),
    ]
