# Generated by Django 6.0 on 2025-12-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('power_usage', models.IntegerField(verbose_name='总功率(W)')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_records', to='power.meter', verbose_name='电表')),
            ],
            options={
                'verbose_name': '实时用电记录',
                'verbose_name_plural': '实时用电记录',
                'db_table': 'realtime_usage',
                'ordering': ['-timestamp'],
            },
        ),
    ]
